CREATE TABLE JOBS(
	JOB_ID STRING PRIMARY KEY,
	RPS NUMBER,
	CONCURRENCY NUMBER,
	DURATION NUMBER,
	STATUS TEXT,
	CREATED_AT TEXT NOT NULL DEFAULT current_timestamp,
	UPDATED_AT TEXT NOT NULL DEFAULT current_timestamp
);

CREATE TABLE JOB_SPAWNS(
	SPAWN_ID STRING PRIMARY KEY,
	JOB_ID STRING,
	STATUS TEXT,

	AVG_LATENCY NUMBER,
	AVG_RPS NUMBER,
	COUNT NUMBER,

	CREATED_AT TEXT NOT NULL DEFAULT current_timestamp,
	UPDATED_AT TEXT NOT NULL DEFAULT current_timestamp
);

CREATE TABLE JOB_SPAWN_METRICS(
	METRIC_ID STRING PRIMARY KEY,
	TICK_NUMBER NUMBER,

	SPAWN_ID STRING KEY,
	JOB_ID STRING,

	LATENCY NUMBER,
	RPS NUMBER,
	COUNT NUMBER,

	CREATED_AT TEXT NOT NULL DEFAULT current_timestamp
);

