import { ACTIVE_STATUSES, AgentPollRequest, AgentPollResponse } from "./types";

/**
 * Agent registry.
 *
 * Replaces the Durable Object / Cloudflare Containers supervisor from the
 * original harness. Load generators now live on external VMs and pull work,
 * so the control plane never starts, stops or reaches into a workload; it
 * only hands out slots and collects reports.
 *
 * Authentication is a single shared token generated by Terraform, injected as
 * the AGENT_TOKEN Worker secret and as VM instance metadata. The previous
 * design minted a per-spawn token inside the Durable Object and never
 * transmitted it, which is why the agent callback endpoints were unreachable.
 */

const IDLE: AgentPollResponse = { action: "idle" };

/**
 * Handle an agent's request for work.
 *
 * Slot claiming is a single conditional INSERT so that concurrent polls from
 * eight VMs cannot oversubscribe a job. An agent that reconnects mid-run gets
 * its existing slot back rather than consuming a second one, because the
 * spawn id is derived from the agent id.
 */
export async function agent_poll(request: Request, env: Env): Promise<AgentPollResponse> {
    const body = await request.json() as AgentPollRequest;

    if (!verify_agent_token(env, body?.token)) {
        throw new UnauthorizedError("invalid agent token");
    }
    if (!body.agentId) {
        return { action: "idle", message: "agentId is required" };
    }

    const job = await env.DB.prepare(
        `SELECT JOB_ID, STATUS, RPS, AGENTS, WORKERS_PER_AGENT, START_AT, STOP_AT, UNTHROTTLED
         FROM JOBS
         WHERE STATUS IN (${ACTIVE_STATUSES.map(() => "?").join(",")})
         ORDER BY CREATED_AT ASC
         LIMIT 1`)
        .bind(...ACTIVE_STATUSES)
        .first();

    if (!job) {
        return IDLE;
    }

    const jobId = job["JOB_ID"] as string;
    const stopAt = job["STOP_AT"] as number;
    const now = Date.now();

    // A job whose window has closed should not attract new agents. The
    // scheduled reaper will finalise it.
    if (now >= stopAt) {
        return IDLE;
    }

    const agents = job["AGENTS"] as number;
    const spawnId = `${jobId}-${body.agentId}`;

    const existing = await env.DB.prepare(
        `SELECT SLOT, STATUS FROM JOB_SPAWNS WHERE SPAWN_ID = ?`)
        .bind(spawnId)
        .first();

    let slot: number;
    if (existing) {
        // Reconnect. Terminal spawns have already done their share.
        if (existing["STATUS"] !== "RUNNING") {
            return IDLE;
        }
        slot = existing["SLOT"] as number;
        await env.DB.prepare(`UPDATE JOB_SPAWNS SET LAST_SEEN = ? WHERE SPAWN_ID = ?`)
            .bind(now, spawnId)
            .run();
    } else {
        // Atomic claim: the row is only inserted while the job still has free
        // slots, and SLOT is assigned from the current occupancy.
        await env.DB.prepare(
            `INSERT INTO JOB_SPAWNS (SPAWN_ID, JOB_ID, AGENT_ID, REGION, STATUS, SLOT, LAST_SEEN, AVG_LATENCY, AVG_RPS, COUNT)
             SELECT ?1, ?2, ?3, ?4, 'RUNNING', (SELECT COUNT(*) FROM JOB_SPAWNS WHERE JOB_ID = ?2), ?5, 0, 0, 0
             WHERE (SELECT COUNT(*) FROM JOB_SPAWNS WHERE JOB_ID = ?2) < ?6
             ON CONFLICT(SPAWN_ID) DO NOTHING`)
            .bind(spawnId, jobId, body.agentId, body.region ?? "unknown", now, agents)
            .run();

        const claimed = await env.DB.prepare(
            `SELECT SLOT FROM JOB_SPAWNS WHERE SPAWN_ID = ?`)
            .bind(spawnId)
            .first();

        if (!claimed) {
            // Job is already fully staffed by other agents.
            return { action: "idle", message: `job ${jobId} has all ${agents} slots filled` };
        }
        slot = claimed["SLOT"] as number;
    }

    if (job["STATUS"] === "QUEUED") {
        await env.DB.prepare(
            `UPDATE JOBS SET STATUS = 'RUNNING', UPDATED_AT = current_timestamp
             WHERE JOB_ID = ? AND STATUS = 'QUEUED'`)
            .bind(jobId)
            .run();
    }

    return {
        action: "run",
        jobId,
        spawnId,
        targetRPS: rps_for_slot(job["RPS"] as number, agents, slot),
        workers: job["WORKERS_PER_AGENT"] as number,
        startAtEpochMs: job["START_AT"] as number,
        stopAtEpochMs: stopAt,
        unthrottled: (job["UNTHROTTLED"] as number) === 1,
    };
}

/**
 * Split the aggregate target across agents, distributing the remainder one
 * request per second at a time so the slices sum exactly to targetRPS.
 */
export function rps_for_slot(targetRPS: number, agents: number, slot: number): number {
    if (agents <= 0) {
        return 0;
    }
    const base = Math.floor(targetRPS / agents);
    const remainder = targetRPS % agents;
    return base + (slot < remainder ? 1 : 0);
}

/** Constant-time-ish comparison so token checks do not leak length or prefix. */
export function verify_agent_token(env: Env, presented: string | undefined): boolean {
    const expected = env.AGENT_TOKEN;
    if (!expected || !presented || presented.length !== expected.length) {
        return false;
    }
    let diff = 0;
    for (let i = 0; i < expected.length; i++) {
        diff |= expected.charCodeAt(i) ^ presented.charCodeAt(i);
    }
    return diff === 0;
}

/** Thrown when a caller presents a bad token; mapped to HTTP 401. */
export class UnauthorizedError extends Error {
    constructor(message: string) {
        super(message);
        this.name = "UnauthorizedError";
    }
}
